### ISSUE TITLE
 No such file or directory: '../msc_tifreaa/gensim/test/test_data/rare_word.txt'

### ISSUE THREAD

**Issue by Clarioooo** [alex-tifrea/poincare_glove#17]
I run 

`./run_glove.sh --train --root /nfs2/liwenbo/glove/poincare_glove --coocc_file /nfs2/liwenbo/glove/poincare_glove/GloVe/cooccurrence.bin --vocab_file /nfs2/liwenbo/glove/poincare_glove/GloVe/vocab.txt --epochs 50 --workers 10 --restrict_vocab 200000 --chunksize 5000 --lr 0.05 --bias --size 100 --dist_func cosh-dist-sq`

but

Traceback (most recent call last):
  File "glove_code/scripts/glove_main.py", line 375, in <module>
    vector_dtype=REAL)
  File "/nfs2/liwenbo/glove/poincare_glove/glove_code/src/glove.py", line 150, in __init__
    self.train()
  File "/nfs2/liwenbo/glove/poincare_glove/glove_code/src/glove.py", line 241, in train
    self._train_epoch(cur_epoch)
  File "/nfs2/liwenbo/glove/poincare_glove/glove_code/src/glove.py", line 224, in _train_epoch
    self._log_epoch_end(cur_epoch, elapsed)
  File "/nfs2/liwenbo/glove/poincare_glove/glove_code/src/glove.py", line 153, in _log_epoch_end
    _, rw_spearman_corr, _ = self.wv.evaluate_word_pairs('../msc_tifreaa/gensim/test/test_data/rare_word.txt')
  File "/nfs2/liwenbo/glove/poincare_glove/gensim/models/keyedvectors.py", line 778, in evaluate_word_pairs
    for line_no, line in enumerate(utils.smart_open(pairs)):
  File "/nfs/liwenbo/anaconda3/envs/glove/lib/python3.7/site-packages/smart_open-7.0.4-py3.7.egg/smart_open/smart_open_lib.py", line 503, in smart_open
    return open(**locals())
  File "/nfs/liwenbo/anaconda3/envs/glove/lib/python3.7/site-packages/smart_open-7.0.4-py3.7.egg/smart_open/smart_open_lib.py", line 184, in open
    newline=newline,
  File "/nfs/liwenbo/anaconda3/envs/glove/lib/python3.7/site-packages/smart_open-7.0.4-py3.7.egg/smart_open/smart_open_lib.py", line 363, in _shortcut_open
    return _builtin_open(local_path, mode, buffering=buffering, **open_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '../msc_tifreaa/gensim/test/test_data/rare_word.txt'
Evaluating model from ../models/glove/glove_baseline/glove_ep50_size100_lr0.05_vocab200000_vanilla_OPTadagrad_COOCCFUNClog_DISTFUNCcosh-dist-sq_bias
INFO:gensim.utils:loading Glove object from ../models/glove/glove_baseline/glove_ep50_size100_lr0.05_vocab200000_vanilla_OPTadagrad_COOCCFUNClog_DISTFUNCcosh-dist-sq_bias
Traceback (most recent call last):
  File "glove_code/scripts/glove_main.py", line 392, in <module>
    model = Glove.load(args.model_filename)
  File "/nfs2/liwenbo/glove/poincare_glove/gensim/utils.py", line 425, in load
    obj = unpickle(fname)
  File "/nfs2/liwenbo/glove/poincare_glove/gensim/utils.py", line 1329, in unpickle
    with smart_open(fname, 'rb') as f:
  File "/nfs/liwenbo/anaconda3/envs/glove/lib/python3.7/site-packages/smart_open-7.0.4-py3.7.egg/smart_open/smart_open_lib.py", line 503, in smart_open
    return open(**locals())
  File "/nfs/liwenbo/anaconda3/envs/glove/lib/python3.7/site-packages/smart_open-7.0.4-py3.7.egg/smart_open/smart_open_lib.py", line 184, in open
    newline=newline,
  File "/nfs/liwenbo/anaconda3/envs/glove/lib/python3.7/site-packages/smart_open-7.0.4-py3.7.egg/smart_open/smart_open_lib.py", line 363, in _shortcut_open
    return _builtin_open(local_path, mode, buffering=buffering, **open_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '../models/glove/glove_baseline/glove_ep50_size100_lr0.05_vocab200000_vanilla_OPTadagrad_COOCCFUNClog_DISTFUNCcosh-dist-sq_bias'

what is ../msc_tifreaa/gensim/test/test_data/rare_word.txt and ../models/glove/glove_baseline/glove_ep50_size100_lr0.05_vocab200000_vanilla_OPTadagrad_COOCCFUNClog_DISTFUNCcosh-dist-sq_bias?

Besides, I have specified the root path, why does it still write '../' instead of 'root_path'

**Comment by Clarioooo** [comment]
@alex-tifrea
